import XCTest
@testable import DagDB

/// AC-3 Australia 3-coloring as an engine-level BACK_EDGE regression.
///
/// Committed upgrade of the daemon-level demo in
/// `examples/ac3_australia/` (see its RUN_RECEIPT.md). The graph is the
/// 96-node encoding from `examples/ac3_australia/dagdb_encoding_spec.md`:
///   - 21 register nodes  (rank 2, ids  0..20) — one domain bit per
///     (region, color); pure state, zero combinational fan-in, driven
///     only by BACK_EDGE latch.
///   - 54 support nodes   (rank 1, ids 21..74) — 2-input OR: "this
///     neighbor still has a color other than `c`".
///   - 21 keep nodes      (rank 0, ids 75..95) — AND of the domain bit
///     and every neighbor support: "this color survives the round".
/// BACK_EDGE keep(R,c) → domain(R,c) latches each round's survivors back
/// into the registers, giving synchronous AC-3. Russell-Norvig Australia
/// map with WA pre-assigned red; converges in 2 synchronous ticks.
///
/// The per-tick truth trajectory is checked against a fixture produced by
/// the pure-Python synchronous AC-3 reference.
final class DagDBAC3Tests: XCTestCase {

    // ── problem definition (mirrors examples/ac3_australia/australia.py) ─

    private static let regions = ["WA", "NT", "SA", "Q", "NSW", "V", "T"]
    private static let colors = ["red", "green", "blue"]  // red=0, green=1, blue=2
    private static let adjacencies: [(String, String)] = [
        ("WA", "NT"), ("WA", "SA"), ("NT", "SA"), ("NT", "Q"),
        ("SA", "Q"), ("SA", "NSW"), ("SA", "V"), ("Q", "NSW"), ("NSW", "V"),
    ]
    private static let preassignment = ["WA": "red"]

    private static func regionIndex(_ r: String) -> Int { regions.firstIndex(of: r)! }

    /// Neighbors of `r`, sorted by region index — the canonical order used
    /// for both support-node ID layout and keep-node wiring.
    private static func neighbors(_ r: String) -> [String] {
        var out: [String] = []
        for (a, b) in adjacencies {
            if a == r { out.append(b) }
            if b == r { out.append(a) }
        }
        return out.sorted { regionIndex($0) < regionIndex($1) }
    }

    // ── LUT6 helpers ─────────────────────────────────────────────────────

    /// AND over the low `n` input slots; higher slots are don't-cares.
    /// bit k set iff the low n bits of k are all 1. n=1 collapses to
    /// identity over slot 0.
    private static func andLUT(_ n: Int) -> UInt64 {
        let mask = (UInt64(1) << UInt64(n)) - 1
        var lut: UInt64 = 0
        for k in 0..<64 where (UInt64(k) & mask) == mask { lut |= (UInt64(1) << UInt64(k)) }
        return lut
    }

    /// 2-input OR on slots 0 and 1: bit k set iff k has bit 0 or bit 1 set.
    private static func or2LUT() -> UInt64 {
        var lut: UInt64 = 0
        for k in 0..<64 where (k & 0b11) != 0 { lut |= (UInt64(1) << UInt64(k)) }
        return lut
    }

    // ── reference trajectory fixture ─────────────────────────────────────
    //
    // 21 register truth bits per tick, in node-ID order
    // (register(region, color) = regionIndex*3 + colorIndex). Ticks 0..3.
    // Tick 0 = initial domains; convergence at tick 2; tick 3 confirms the
    // fixed point holds. generated by examples/ac3_australia/reference_ac3.py
    // on 2026-07-07.
    private static let referenceTrajectory: [[UInt8]] = [
        // tick 0 (initial): WA={red}, all others = all three colors
        [1, 0, 0,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1],
        // tick 1: NT and SA lose red; rest unchanged
        [1, 0, 0,  0, 1, 1,  0, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1],
        // tick 2 (converged): identical to tick 1
        [1, 0, 0,  0, 1, 1,  0, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1],
        // tick 3 (fixed point holds): identical to tick 2
        [1, 0, 0,  0, 1, 1,  0, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1,  1, 1, 1],
    ]

    // ── the acceptance test ──────────────────────────────────────────────

    func testAC3AustraliaMatchesReferenceTrajectory() throws {
        let regions = Self.regions
        let colors = Self.colors

        // ID layout: registers 0..20, supports 21..74, keeps 75..95.
        var registerID: [String: Int] = [:]      // key "region|color"
        var supportID: [String: Int] = [:]        // key "region|color|neighbor"
        var keepID: [String: Int] = [:]
        func rk(_ r: String, _ c: String) -> String { "\(r)|\(c)" }
        func sk(_ r: String, _ c: String, _ n: String) -> String { "\(r)|\(c)|\(n)" }

        let g = DagDBGraph()

        // 1) Register nodes (rank 2), ordered by (region, color). Initial
        //    truth from initial_domains(): WA={red}, all others all-three.
        for r in regions {
            for c in colors {
                let truth: Bool
                if let pre = Self.preassignment[r] { truth = (c == pre) } else { truth = true }
                let id = g.addLeaf(label: "dom_\(r)_\(c)", rank: 2, truth: truth)
                XCTAssertEqual(id, Self.regionIndex(r) * 3 + colors.firstIndex(of: c)!)
                registerID[rk(r, c)] = id
            }
        }

        // 2) Support nodes (rank 1), ordered by (region, color, neighbor).
        let or2 = Self.or2LUT()
        for r in regions {
            for c in colors {
                for n in Self.neighbors(r) {
                    let id = g.addGate(label: "sup_\(r)_\(c)_\(n)", rank: 1, lut6: or2)
                    supportID[sk(r, c, n)] = id
                }
            }
        }
        XCTAssertEqual(g.nodeCount, 75, "supports must end at ID 75")

        // 3) Keep nodes (rank 0), parallel to register layout. AND of
        //    (1 + |neighbors|) inputs.
        for r in regions {
            let fanin = 1 + Self.neighbors(r).count
            let lut = Self.andLUT(fanin)
            for c in colors {
                let id = g.addGate(label: "keep_\(r)_\(c)", rank: 0, lut6: lut)
                keepID[rk(r, c)] = id
            }
        }
        XCTAssertEqual(g.nodeCount, 96, "graph must have 96 nodes")

        // 4) Support wiring: inputs are the neighbor's two other-color
        //    domain bits, slot 0 = lower-index other color.
        for r in regions {
            for c in colors {
                let other = colors.filter { $0 != c }
                for n in Self.neighbors(r) {
                    let sid = supportID[sk(r, c, n)]!
                    try g.connect(from: registerID[rk(n, other[0])]!, to: sid)
                    try g.connect(from: registerID[rk(n, other[1])]!, to: sid)
                }
            }
        }

        // 5) Keep wiring: slot 0 = domain(R,c); slots 1.. = the supports.
        for r in regions {
            for c in colors {
                let kid = keepID[rk(r, c)]!
                try g.connect(from: registerID[rk(r, c)]!, to: kid)
                for n in Self.neighbors(r) {
                    try g.connect(from: supportID[sk(r, c, n)]!, to: kid)
                }
            }
        }

        // 6) BACK_EDGEs: keep(R,c) → domain(R,c).
        for r in regions {
            for c in colors {
                try g.connectBack(from: keepID[rk(r, c)]!, to: registerID[rk(r, c)]!)
            }
        }

        XCTAssertTrue(g.validate().isEmpty, "AC-3 graph must validate clean")

        let engine = try DagDBEngine(graph: g)
        XCTAssertEqual(engine.backEdgeCount, 21, "one BACK_EDGE per register")

        func registerBits() -> [UInt8] {
            let s = engine.readTruthStates()
            return (0..<21).map { s[$0] }
        }

        // Tick 0 = initial state, before any tick.
        XCTAssertEqual(registerBits(), Self.referenceTrajectory[0],
                       "tick 0 (initial) must match reference")

        // Ticks 1..3: combinational pass + BACK_EDGE latch each tick.
        for tick in 1...3 {
            engine.tick(tickNumber: UInt32(tick))
            XCTAssertEqual(registerBits(), Self.referenceTrajectory[tick],
                           "tick \(tick) registers must match reference trajectory")
        }
    }
}
